name: Build and Deploy

on:
  push:
    branches:
      - main
      - master

jobs:
  publish-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: '@dculussoftwares'
      - run: npm install
      - run: npm run build
      - run: cd build && npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
